### ISSUE TITLE
Detect Bridging should be enabled by default

### ISSUE THREAD

**Issue by Technofrikus** [prusa3d/PrusaSlicer-settings#103]
### Version
2.2.0+

### Operating system type + version
MacOS

### 3D printer brand / version + firmware version (if known)
MK3s

### Behavior
In most if not all default print profiles "detect bridging perimeters" is disabled by default. I am not sure why, because I dont see a downside, only upsides.
I try to print without supports when possible. So bridging helps a lot in this. I made custom profiles, but I think it would be best if it would be enabled by default.

**Comment by rtyr** [comment]
I don't think it should be enabled by default since it is using significantly different flow. 

See for example:
https://github.com/prusa3d/PrusaSlicer/issues/2415
https://github.com/prusa3d/PrusaSlicer/issues/767

We will leave it disabled for now. Closing.
