### ISSUE TITLE
Start gcode Some Creality printers prob bed before heated

### ISSUE THREAD

**Issue by hdtechk** [prusa3d/PrusaSlicer-settings#107]
M190 S[first_layer_bed_temperature] ; wait for bed temp
Needs to be moved before G28 so heated bed is ready before G29 runs.
found when using CR 10s PRO profile and PrusaSlicer 2.3.0 alpha3

**Comment by rtyr** [comment]
@pmjdebruijn Could you please look at this?

**Comment by pmjdebruijn** [comment]
The reason why this is currently done in parallel, is that it increases print start speed by a fairly large margin. And I've never seen issues because of it at least on an Ender 3.

So the question is, are you actually experiencing first layer issues because of this?

**Comment by pmjdebruijn** [comment]
#5114 will probably offer a reasonably compromise

**Comment by hdtechk** [comment]
Thanks for looking at this. Yes when I manually moved the M190 it made big differences in my first layer.
