### ISSUE TITLE
Artillery Profile

### ISSUE THREAD

**Issue by SzabolcsHornyak** [prusa3d/PrusaSlicer-settings#117]
Hello Dev Team,
I made profiles for Artillery X1 and Genius with Bed textures, Bed STL, and few preset.
Please give a right to upload my branch.

Best Regards,
Szabolcs

**Comment by rtyr** [comment]
Hi. You can either create the pull request or just zip it and attach it to this issue.

**Comment by rtyr** [comment]
Pull request created https://github.com/prusa3d/PrusaSlicer-settings/pull/118. I am closing this issue.
