### ISSUE TITLE
Ghosting problems when using PrusaSlicer–generated G-Code, on Prusa MINI

### ISSUE THREAD

**Issue by PaperVolume** [prusa3d/PrusaSlicer-settings#124]
### Version
_2.3.0_

### Operating system type + version
_Windows 10, 64-bit & 32-bit #s_
_In case of 3D rendering issues, please attach the content of menu Help -> System Info dialog_

### 3D printer brand / version + firmware version (if known)
_Original Prusa MINI, partially assembled, with a 0.25mm nozzle, on firmware 4.2.1 & 4.3.0 #s_

### Behavior
* _Severe ghosting appears when model is printed and sliced with PrusaSlicer. Cura 3D has no such problem. As far as I know this is completely independent from seam position_
* _Every G-Code generated with PrusaSlicer exhibits this behavior so far._
* _Ghosting always visible on supports, with intensity increasing as layer height decreases (none on 0.15mm, visible on 0.07mm)_
* _As expected_
  * _![obraz](https://user-images.githubusercontent.com/79140235/108048922-ead8d580-7047-11eb-9825-4c8825507512.png)_

#### Project File (.3MF) where problem occurs (example)
_[100_StrikeDagger_LowerArm_SlideArm_01.zip](https://github.com/prusa3d/PrusaSlicer/files/5987812/100_StrikeDagger_LowerArm_SlideArm_01.zip)_
_![IMG_20210215_190218](https://user-images.githubusercontent.com/79140235/108048160-fb3c8080-7046-11eb-8611-b80eaf61cd76.jpg)
_

**Comment by PaperVolume** [comment]
@rtyr Thank you for your reply. I have increased extrusion width from 0.2mm to 0.3mm, but increasing extrusion multiplier seemed to yield better results on supports.

**Comment by rtyr** [comment]
Maybe your MINI is underextruding a little bit.

**Comment by PaperVolume** [comment]
Right after this problem first occured I made every hardware fix I could find. I found my way here through Prusa support and a common assumption was that this is indeed a slicer issue, considering Cura doesn't show these problems. Previously these settings weren't doing anything out of normal, which is weird because this indicates a maintenance issue, and they were all redundantly adressed.

**Comment by rtyr** [comment]
It is not so easily comparable, since PrusaSlicer uses variable layer height for the supports, independent from main object's layer height. If it printed fine before, then likely something has changed on the printer side.
