### ISSUE TITLE
Anet ET4 profile for prusa slicer

### ISSUE THREAD

**Issue by TecXXI** [prusa3d/PrusaSlicer-settings#126]
# generated by PrusaSlicer 2.3.0+win64 on 2021-02-28 at 05:26:27 UTC

[print:0.05mm]
avoid_crossing_perimeters = 0
avoid_crossing_perimeters_max_detour = 0
bottom_fill_pattern = monotonic
bottom_solid_layers = 3
bottom_solid_min_thickness = 0
bridge_acceleration = 300
bridge_angle = 0
bridge_flow_ratio = 0.7
bridge_speed = 20
brim_width = 0
clip_multipart_objects = 1
compatible_printers = 
compatible_printers_condition = 
complete_objects = 0
default_acceleration = 1000
dont_support_bridges = 1
draft_shield = 0
elefant_foot_compensation = 0.2
ensure_vertical_shell_thickness = 0
external_perimeter_extrusion_width = 0.45
external_perimeter_speed = 20
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 45
extrusion_width = 0.45
fill_angle = 45
fill_density = 15%
fill_pattern = gyroid
first_layer_acceleration = 500
first_layer_extrusion_width = 0.42
first_layer_height = 0.35
first_layer_speed = 20
gap_fill_speed = 20
gcode_comments = 0
gcode_label_objects = 1
infill_acceleration = 800
infill_anchor = 2.5
infill_anchor_max = 12
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.45
infill_first = 0
infill_only_where_needed = 0
infill_overlap = 25%
infill_speed = 30
inherits = 
interface_shells = 0
ironing = 0
ironing_flowrate = 15%
ironing_spacing = 0.1
ironing_speed = 15
ironing_type = top
layer_height = 0.3
max_print_speed = 80
max_volumetric_speed = 0
min_skirt_length = 4
notes = 
only_retract_when_crossing_perimeters = 0
ooze_prevention = 0
output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
overhangs = 1
perimeter_acceleration = 300
perimeter_extruder = 1
perimeter_extrusion_width = 0.45
perimeter_speed = 30
perimeters = 3
post_process = 
print_settings_id = 
raft_layers = 0
resolution = 0
seam_position = aligned
single_extruder_multi_material_priming = 0
skirt_distance = 2
skirt_height = 3
skirts = 1
slice_closing_radius = 0.049
small_perimeter_speed = 20
solid_infill_below_area = 0
solid_infill_every_layers = 0
solid_infill_extruder = 1
solid_infill_extrusion_width = 0.45
solid_infill_speed = 30
spiral_vase = 0
standby_temperature_delta = -5
support_material = 0
support_material_angle = 0
support_material_auto = 1
support_material_buildplate_only = 0
support_material_contact_distance = 0.1
support_material_enforce_layers = 0
support_material_extruder = 0
support_material_extrusion_width = 0.3
support_material_interface_contact_loops = 0
support_material_interface_extruder = 0
support_material_interface_layers = 2
support_material_interface_spacing = 0.2
support_material_interface_speed = 100%
support_material_pattern = rectilinear
support_material_spacing = 1.5
support_material_speed = 30
support_material_synchronize_layers = 0
support_material_threshold = 55
support_material_with_sheath = 0
support_material_xy_spacing = 50%
thin_walls = 1
threads = 2
top_fill_pattern = monotonic
top_infill_extrusion_width = 0.4
top_solid_infill_speed = 20
top_solid_layers = 3
top_solid_min_thickness = 0
travel_speed = 180
wipe_tower = 1
wipe_tower_bridging = 10
wipe_tower_no_sparse_layers = 0
wipe_tower_rotation_angle = 0
wipe_tower_width = 60
wipe_tower_x = 170
wipe_tower_y = 125
xy_size_compensation = 0

[print:0.07mm]
avoid_crossing_perimeters = 0
avoid_crossing_perimeters_max_detour = 0
bottom_fill_pattern = monotonic
bottom_solid_layers = 3
bottom_solid_min_thickness = 0
bridge_acceleration = 300
bridge_angle = 0
bridge_flow_ratio = 0.7
bridge_speed = 20
brim_width = 0
clip_multipart_objects = 1
compatible_printers = 
compatible_printers_condition = 
complete_objects = 0
default_acceleration = 1000
dont_support_bridges = 1
draft_shield = 0
elefant_foot_compensation = 0.2
ensure_vertical_shell_thickness = 0
external_perimeter_extrusion_width = 0.45
external_perimeter_speed = 20
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 45
extrusion_width = 0.45
fill_angle = 45
fill_density = 15%
fill_pattern = gyroid
first_layer_acceleration = 500
first_layer_extrusion_width = 0.42
first_layer_height = 0.35
first_layer_speed = 20
gap_fill_speed = 20
gcode_comments = 0
gcode_label_objects = 1
infill_acceleration = 800
infill_anchor = 2.5
infill_anchor_max = 12
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.45
infill_first = 0
infill_only_where_needed = 0
infill_overlap = 25%
infill_speed = 40
inherits = 
interface_shells = 0
ironing = 0
ironing_flowrate = 15%
ironing_spacing = 0.1
ironing_speed = 15
ironing_type = top
layer_height = 0.3
max_print_speed = 80
max_volumetric_speed = 0
min_skirt_length = 4
notes = 
only_retract_when_crossing_perimeters = 0
ooze_prevention = 0
output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
overhangs = 1
perimeter_acceleration = 300
perimeter_extruder = 1
perimeter_extrusion_width = 0.45
perimeter_speed = 30
perimeters = 3
post_process = 
print_settings_id = 
raft_layers = 0
resolution = 0
seam_position = aligned
single_extruder_multi_material_priming = 0
skirt_distance = 2
skirt_height = 3
skirts = 1
slice_closing_radius = 0.049
small_perimeter_speed = 20
solid_infill_below_area = 0
solid_infill_every_layers = 0
solid_infill_extruder = 1
solid_infill_extrusion_width = 0.45
solid_infill_speed = 40
spiral_vase = 0
standby_temperature_delta = -5
support_material = 0
support_material_angle = 0
support_material_auto = 1
support_material_buildplate_only = 0
support_material_contact_distance = 0.1
support_material_enforce_layers = 0
support_material_extruder = 0
support_material_extrusion_width = 0.3
support_material_interface_contact_loops = 0
support_material_interface_extruder = 0
support_material_interface_layers = 2
support_material_interface_spacing = 0.2
support_material_interface_speed = 100%
support_material_pattern = rectilinear
support_material_spacing = 1.5
support_material_speed = 40
support_material_synchronize_layers = 0
support_material_threshold = 55
support_material_with_sheath = 0
support_material_xy_spacing = 50%
thin_walls = 1
threads = 2
top_fill_pattern = monotonic
top_infill_extrusion_width = 0.4
top_solid_infill_speed = 30
top_solid_layers = 3
top_solid_min_thickness = 0
travel_speed = 180
wipe_tower = 1
wipe_tower_bridging = 10
wipe_tower_no_sparse_layers = 0
wipe_tower_rotation_angle = 0
wipe_tower_width = 60
wipe_tower_x = 170
wipe_tower_y = 125
xy_size_compensation = 0

[print:0.10mm]
avoid_crossing_perimeters = 0
avoid_crossing_perimeters_max_detour = 0
bottom_fill_pattern = monotonic
bottom_solid_layers = 3
bottom_solid_min_thickness = 0
bridge_acceleration = 1000
bridge_angle = 0
bridge_flow_ratio = 0.7
bridge_speed = 30
brim_width = 0
clip_multipart_objects = 1
compatible_printers = 
compatible_printers_condition = 
complete_objects = 0
default_acceleration = 1000
dont_support_bridges = 1
draft_shield = 0
elefant_foot_compensation = 0.2
ensure_vertical_shell_thickness = 0
external_perimeter_extrusion_width = 0.45
external_perimeter_speed = 25
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 45
extrusion_width = 0.45
fill_angle = 45
fill_density = 15%
fill_pattern = gyroid
first_layer_acceleration = 1000
first_layer_extrusion_width = 0.42
first_layer_height = 0.35
first_layer_speed = 20
gap_fill_speed = 40
gcode_comments = 0
gcode_label_objects = 1
infill_acceleration = 1000
infill_anchor = 2.5
infill_anchor_max = 12
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.45
infill_first = 0
infill_only_where_needed = 0
infill_overlap = 25%
infill_speed = 80
inherits = 
interface_shells = 0
ironing = 0
ironing_flowrate = 15%
ironing_spacing = 0.1
ironing_speed = 15
ironing_type = top
layer_height = 0.3
max_print_speed = 150
max_volumetric_speed = 0
min_skirt_length = 4
notes = 
only_retract_when_crossing_perimeters = 0
ooze_prevention = 0
output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
overhangs = 1
perimeter_acceleration = 800
perimeter_extruder = 1
perimeter_extrusion_width = 0.45
perimeter_speed = 45
perimeters = 3
post_process = 
print_settings_id = 
raft_layers = 0
resolution = 0
seam_position = aligned
single_extruder_multi_material_priming = 0
skirt_distance = 2
skirt_height = 3
skirts = 1
slice_closing_radius = 0.049
small_perimeter_speed = 25
solid_infill_below_area = 0
solid_infill_every_layers = 0
solid_infill_extruder = 1
solid_infill_extrusion_width = 0.45
solid_infill_speed = 80
spiral_vase = 0
standby_temperature_delta = -5
support_material = 0
support_material_angle = 0
support_material_auto = 1
support_material_buildplate_only = 0
support_material_contact_distance = 0.1
support_material_enforce_layers = 0
support_material_extruder = 0
support_material_extrusion_width = 0.35
support_material_interface_contact_loops = 0
support_material_interface_extruder = 0
support_material_interface_layers = 2
support_material_interface_spacing = 0.2
support_material_interface_speed = 100%
support_material_pattern = rectilinear
support_material_spacing = 2
support_material_speed = 50
support_material_synchronize_layers = 0
support_material_threshold = 55
support_material_with_sheath = 0
support_material_xy_spacing = 50%
thin_walls = 1
threads = 2
top_fill_pattern = monotonic
top_infill_extrusion_width = 0.4
top_solid_infill_speed = 40
top_solid_layers = 3
top_solid_min_thickness = 0
travel_speed = 180
wipe_tower = 1
wipe_tower_bridging = 10
wipe_tower_no_sparse_layers = 0
wipe_tower_rotation_angle = 0
wipe_tower_width = 60
wipe_tower_x = 170
wipe_tower_y = 125
xy_size_compensation = 0

[print:0.15mm]
avoid_crossing_perimeters = 0
avoid_crossing_perimeters_max_detour = 0
bottom_fill_pattern = monotonic
bottom_solid_layers = 3
bottom_solid_min_thickness = 0
bridge_acceleration = 1000
bridge_angle = 0
bridge_flow_ratio = 0.8
bridge_speed = 30
brim_width = 0
clip_multipart_objects = 1
compatible_printers = 
compatible_printers_condition = 
complete_objects = 0
default_acceleration = 1000
dont_support_bridges = 1
draft_shield = 0
elefant_foot_compensation = 0.2
ensure_vertical_shell_thickness = 0
external_perimeter_extrusion_width = 0.45
external_perimeter_speed = 25
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 45
extrusion_width = 0.45
fill_angle = 45
fill_density = 15%
fill_pattern = gyroid
first_layer_acceleration = 1000
first_layer_extrusion_width = 0.42
first_layer_height = 0.35
first_layer_speed = 20
gap_fill_speed = 40
gcode_comments = 0
gcode_label_objects = 1
infill_acceleration = 1000
infill_anchor = 2.5
infill_anchor_max = 12
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.45
infill_first = 0
infill_only_where_needed = 0
infill_overlap = 25%
infill_speed = 80
inherits = 
interface_shells = 0
ironing = 0
ironing_flowrate = 15%
ironing_spacing = 0.1
ironing_speed = 15
ironing_type = top
layer_height = 0.3
max_print_speed = 150
max_volumetric_speed = 0
min_skirt_length = 4
notes = 
only_retract_when_crossing_perimeters = 0
ooze_prevention = 0
output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
overhangs = 1
perimeter_acceleration = 800
perimeter_extruder = 1
perimeter_extrusion_width = 0.45
perimeter_speed = 45
perimeters = 3
post_process = 
print_settings_id = 
raft_layers = 0
resolution = 0
seam_position = aligned
single_extruder_multi_material_priming = 0
skirt_distance = 2
skirt_height = 3
skirts = 1
slice_closing_radius = 0.049
small_perimeter_speed = 25
solid_infill_below_area = 0
solid_infill_every_layers = 0
solid_infill_extruder = 1
solid_infill_extrusion_width = 0.45
solid_infill_speed = 80
spiral_vase = 0
standby_temperature_delta = -5
support_material = 0
support_material_angle = 0
support_material_auto = 1
support_material_buildplate_only = 0
support_material_contact_distance = 0.1
support_material_enforce_layers = 0
support_material_extruder = 0
support_material_extrusion_width = 0.35
support_material_interface_contact_loops = 0
support_material_interface_extruder = 0
support_material_interface_layers = 2
support_material_interface_spacing = 0.2
support_material_interface_speed = 100%
support_material_pattern = rectilinear
support_material_spacing = 2
support_material_speed = 50
support_material_synchronize_layers = 0
support_material_threshold = 55
support_material_with_sheath = 0
support_material_xy_spacing = 50%
thin_walls = 1
threads = 2
top_fill_pattern = monotonic
top_infill_extrusion_width = 0.4
top_solid_infill_speed = 40
top_solid_layers = 3
top_solid_min_thickness = 0
travel_speed = 180
wipe_tower = 1
wipe_tower_bridging = 10
wipe_tower_no_sparse_layers = 0
wipe_tower_rotation_angle = 0
wipe_tower_width = 60
wipe_tower_x = 170
wipe_tower_y = 125
xy_size_compensation = 0

[print:0.20mm - Default]
avoid_crossing_perimeters = 0
avoid_crossing_perimeters_max_detour = 0
bottom_fill_pattern = monotonic
bottom_solid_layers = 3
bottom_solid_min_thickness = 0
bridge_acceleration = 1000
bridge_angle = 0
bridge_flow_ratio = 0.95
bridge_speed = 30
brim_width = 0
clip_multipart_objects = 1
compatible_printers = 
compatible_printers_condition = 
complete_objects = 0
default_acceleration = 1000
dont_support_bridges = 1
draft_shield = 0
elefant_foot_compensation = 0.2
ensure_vertical_shell_thickness = 0
external_perimeter_extrusion_width = 0.45
external_perimeter_speed = 25
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 45
extrusion_width = 0.45
fill_angle = 45
fill_density = 15%
fill_pattern = adaptivecubic
first_layer_acceleration = 1000
first_layer_extrusion_width = 0.42
first_layer_height = 0.35
first_layer_speed = 20
gap_fill_speed = 40
gcode_comments = 0
gcode_label_objects = 1
infill_acceleration = 1000
infill_anchor = 2.5
infill_anchor_max = 12
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.45
infill_first = 0
infill_only_where_needed = 0
infill_overlap = 25%
infill_speed = 60
inherits = 
interface_shells = 0
ironing = 0
ironing_flowrate = 15%
ironing_spacing = 0.1
ironing_speed = 15
ironing_type = top
layer_height = 0.3
max_print_speed = 80
max_volumetric_speed = 0
min_skirt_length = 4
notes = 
only_retract_when_crossing_perimeters = 0
ooze_prevention = 0
output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
overhangs = 1
perimeter_acceleration = 800
perimeter_extruder = 1
perimeter_extrusion_width = 0.45
perimeter_speed = 45
perimeters = 3
post_process = 
print_settings_id = 
raft_layers = 0
resolution = 0
seam_position = aligned
single_extruder_multi_material_priming = 0
skirt_distance = 2
skirt_height = 3
skirts = 1
slice_closing_radius = 0.049
small_perimeter_speed = 25
solid_infill_below_area = 0
solid_infill_every_layers = 0
solid_infill_extruder = 1
solid_infill_extrusion_width = 0.45
solid_infill_speed = 60
spiral_vase = 0
standby_temperature_delta = -5
support_material = 0
support_material_angle = 0
support_material_auto = 1
support_material_buildplate_only = 0
support_material_contact_distance = 0.1
support_material_enforce_layers = 0
support_material_extruder = 0
support_material_extrusion_width = 0.35
support_material_interface_contact_loops = 0
support_material_interface_extruder = 0
support_material_interface_layers = 2
support_material_interface_spacing = 0.2
support_material_interface_speed = 100%
support_material_pattern = rectilinear
support_material_spacing = 2
support_material_speed = 50
support_material_synchronize_layers = 0
support_material_threshold = 40
support_material_with_sheath = 0
support_material_xy_spacing = 50%
thin_walls = 1
threads = 2
top_fill_pattern = monotonic
top_infill_extrusion_width = 0.4
top_solid_infill_speed = 40
top_solid_layers = 3
top_solid_min_thickness = 0
travel_speed = 80
wipe_tower = 1
wipe_tower_bridging = 10
wipe_tower_no_sparse_layers = 0
wipe_tower_rotation_angle = 0
wipe_tower_width = 60
wipe_tower_x = 170
wipe_tower_y = 125
xy_size_compensation = 0

[print:0.30mm]
avoid_crossing_perimeters = 0
avoid_crossing_perimeters_max_detour = 0
bottom_fill_pattern = monotonic
bottom_solid_layers = 3
bottom_solid_min_thickness = 0
bridge_acceleration = 1000
bridge_angle = 0
bridge_flow_ratio = 0.95
bridge_speed = 30
brim_width = 0
clip_multipart_objects = 1
compatible_printers = 
compatible_printers_condition = 
complete_objects = 0
default_acceleration = 1000
dont_support_bridges = 1
draft_shield = 0
elefant_foot_compensation = 0.2
ensure_vertical_shell_thickness = 0
external_perimeter_extrusion_width = 0.6
external_perimeter_speed = 35
external_perimeters_first = 0
extra_perimeters = 1
extruder_clearance_height = 20
extruder_clearance_radius = 45
extrusion_width = 0.5
fill_angle = 45
fill_density = 20%
fill_pattern = grid
first_layer_acceleration = 1000
first_layer_extrusion_width = 0.42
first_layer_height = 0.35
first_layer_speed = 20
gap_fill_speed = 40
gcode_comments = 0
gcode_label_objects = 1
infill_acceleration = 1000
infill_anchor = 2.5
infill_anchor_max = 12
infill_every_layers = 1
infill_extruder = 1
infill_extrusion_width = 0.5
infill_first = 0
infill_only_where_needed = 0
infill_overlap = 25%
infill_speed = 85
inherits = 
interface_shells = 0
ironing = 0
ironing_flowrate = 15%
ironing_spacing = 0.1
ironing_speed = 15
ironing_type = top
layer_height = 0.3
max_print_speed = 100
max_volumetric_speed = 0
min_skirt_length = 4
notes = 
only_retract_when_crossing_perimeters = 0
ooze_prevention = 0
output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
overhangs = 1
perimeter_acceleration = 800
perimeter_extruder = 1
perimeter_extrusion_width = 0.5
perimeter_speed = 50
perimeters = 3
post_process = 
print_settings_id = 
raft_layers = 0
resolution = 0
seam_position = aligned
single_extruder_multi_material_priming = 0
skirt_distance = 2
skirt_height = 3
skirts = 1
slice_closing_radius = 0.049
small_perimeter_speed = 30
solid_infill_below_area = 0
solid_infill_every_layers = 0
solid_infill_extruder = 1
solid_infill_extrusion_width = 0.5
solid_infill_speed = 80
spiral_vase = 0
standby_temperature_delta = -5
support_material = 0
support_material_angle = 0
support_material_auto = 1
support_material_buildplate_only = 0
support_material_contact_distance = 0.1
support_material_enforce_layers = 0
support_material_extruder = 0
support_material_extrusion_width = 0.38
support_material_interface_contact_loops = 0
support_material_interface_extruder = 0
support_material_interface_layers = 2
support_material_interface_spacing = 0.2
support_material_interface_speed = 100%
support_material_pattern = rectilinear
support_material_spacing = 2
support_material_speed = 45
support_material_synchronize_layers = 0
support_material_threshold = 55
support_material_with_sheath = 0
support_material_xy_spacing = 50%
thin_walls = 1
threads = 2
top_fill_pattern = monotonic
top_infill_extrusion_width = 0.45
top_solid_infill_speed = 40
top_solid_layers = 3
top_solid_min_thickness = 0
travel_speed = 180
wipe_tower = 1
wipe_tower_bridging = 10
wipe_tower_no_sparse_layers = 0
wipe_tower_rotation_angle = 0
wipe_tower_width = 60
wipe_tower_x = 170
wipe_tower_y = 125
xy_size_compensation = 0

[filament:TuCAB ABS]
bed_temperature = 80
bridge_fan_speed = 100
compatible_printers = 
compatible_printers_condition = 
compatible_prints = 
compatible_prints_condition = 
cooling = 1
disable_fan_first_layers = 3
end_filament_gcode = ""
extrusion_multiplier = 1.18
fan_always_on = 0
fan_below_layer_time = 60
filament_colour = #C0C0C0
filament_cooling_final_speed = 3.4
filament_cooling_initial_speed = 2.2
filament_cooling_moves = 4
filament_cost = 14.6
filament_density = 1.07
filament_deretract_speed = nil
filament_diameter = 1.75
filament_load_time = 0
filament_loading_speed = 28
filament_loading_speed_start = 3
filament_max_volumetric_speed = 11
filament_minimal_purge_on_wipe_tower = 15
filament_notes = ""
filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
filament_retract_before_travel = nil
filament_retract_before_wipe = nil
filament_retract_layer_change = nil
filament_retract_length = 6.5
filament_retract_lift = nil
filament_retract_lift_above = nil
filament_retract_lift_below = nil
filament_retract_restart_extra = nil
filament_retract_speed = 25
filament_settings_id = ""
filament_soluble = 0
filament_spool_weight = 1000
filament_toolchange_delay = 0
filament_type = ABS
filament_unload_time = 0
filament_unloading_speed = 90
filament_unloading_speed_start = 100
filament_vendor = (Unknown)
filament_wipe = nil
first_layer_bed_temperature = 80
first_layer_temperature = 230
full_fan_speed_layer = 0
inherits = 
max_fan_speed = 100
min_fan_speed = 35
min_print_speed = 10
slowdown_below_layer_time = 5
start_filament_gcode = "\n"
temperature = 230

[filament:TuCAB PETG]
bed_temperature = 70
bridge_fan_speed = 100
compatible_printers = 
compatible_printers_condition = 
compatible_prints = 
compatible_prints_condition = 
cooling = 1
disable_fan_first_layers = 3
end_filament_gcode = "\n"
extrusion_multiplier = 1.18
fan_always_on = 0
fan_below_layer_time = 60
filament_colour = #0000FF
filament_cooling_final_speed = 3.4
filament_cooling_initial_speed = 2.2
filament_cooling_moves = 4
filament_cost = 14.6
filament_density = 1.38
filament_deretract_speed = nil
filament_diameter = 1.75
filament_load_time = 0
filament_loading_speed = 28
filament_loading_speed_start = 3
filament_max_volumetric_speed = 8
filament_minimal_purge_on_wipe_tower = 15
filament_notes = ""
filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
filament_retract_before_travel = nil
filament_retract_before_wipe = nil
filament_retract_layer_change = nil
filament_retract_length = 6.5
filament_retract_lift = nil
filament_retract_lift_above = nil
filament_retract_lift_below = nil
filament_retract_restart_extra = nil
filament_retract_speed = 25
filament_settings_id = ""
filament_soluble = 0
filament_spool_weight = 1000
filament_toolchange_delay = 0
filament_type = PET
filament_unload_time = 0
filament_unloading_speed = 90
filament_unloading_speed_start = 100
filament_vendor = (Unknown)
filament_wipe = nil
first_layer_bed_temperature = 70
first_layer_temperature = 235
full_fan_speed_layer = 0
inherits = 
max_fan_speed = 50
min_fan_speed = 25
min_print_speed = 10
slowdown_below_layer_time = 5
start_filament_gcode = "\n"
temperature = 235

[filament:TuCAB PLA]
bed_temperature = 60
bridge_fan_speed = 100
compatible_printers = 
compatible_printers_condition = 
compatible_prints = 
compatible_prints_condition = 
cooling = 1
disable_fan_first_layers = 3
end_filament_gcode = ""
extrusion_multiplier = 1.18
fan_always_on = 0
fan_below_layer_time = 60
filament_colour = #FFFF00
filament_cooling_final_speed = 3.4
filament_cooling_initial_speed = 2.2
filament_cooling_moves = 4
filament_cost = 14.6
filament_density = 1.24
filament_deretract_speed = nil
filament_diameter = 1.75
filament_load_time = 0
filament_loading_speed = 28
filament_loading_speed_start = 3
filament_max_volumetric_speed = 15
filament_minimal_purge_on_wipe_tower = 15
filament_notes = ""
filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
filament_retract_before_travel = nil
filament_retract_before_wipe = nil
filament_retract_layer_change = nil
filament_retract_length = 6.5
filament_retract_lift = nil
filament_retract_lift_above = nil
filament_retract_lift_below = nil
filament_retract_restart_extra = nil
filament_retract_speed = 25
filament_settings_id = ""
filament_soluble = 0
filament_spool_weight = 1000
filament_toolchange_delay = 0
filament_type = PLA
filament_unload_time = 0
filament_unloading_speed = 90
filament_unloading_speed_start = 100
filament_vendor = (Unknown)
filament_wipe = nil
first_layer_bed_temperature = 60
first_layer_temperature = 200
full_fan_speed_layer = 0
inherits = 
max_fan_speed = 100
min_fan_speed = 35
min_print_speed = 10
slowdown_below_layer_time = 5
start_filament_gcode = "\n"
temperature = 200

[printer:Anet ET4]
bed_custom_model = C:\\Program Files\\Prusa3D\\PrusaSlicer\\resources\\profiles\\Creality\\ender3_bed.stl
bed_custom_texture = 
bed_shape = 0x0,220x0,220x220,0x220
before_layer_gcode = 
between_objects_gcode = 
color_change_gcode = M600
cooling_tube_length = 5
cooling_tube_retraction = 91.5
default_filament_profile = 
default_print_profile = 
deretract_speed = 0
end_gcode = M104 S0 ;extruder heater off\nM140 S0 ;heated bed heater off (if you have it)\nG91 ;relative positioning\nG1 E-1 F300  ;retract the filament a bit before lifting the nozzle, to release some of the pressure\nG1 Z+0.5 E-5 X-20 Y-20 F9000 ;move Z up a bit and retract filament even more\nG28 X0 Y0 ;move X/Y to min endstops, so the head is out of the way\nG1 Y210 F9000 ;move out to get part off\nM84 ;steppers off\nG90 ;absolute positioning
extra_loading_move = -2
extruder_colour = ""
extruder_offset = 0x0
gcode_flavor = marlin
high_current_on_filament_swap = 0
host_type = octoprint
inherits = 
layer_gcode = 
machine_limits_usage = time_estimate_only
machine_max_acceleration_e = 10000,5000
machine_max_acceleration_extruding = 1500,1250
machine_max_acceleration_retracting = 1500,1250
machine_max_acceleration_x = 9000,1000
machine_max_acceleration_y = 9000,1000
machine_max_acceleration_z = 500,200
machine_max_feedrate_e = 120,120
machine_max_feedrate_x = 500,200
machine_max_feedrate_y = 500,200
machine_max_feedrate_z = 12,12
machine_max_jerk_e = 2.5,2.5
machine_max_jerk_x = 10,10
machine_max_jerk_y = 10,10
machine_max_jerk_z = 0.2,0.4
machine_min_extruding_rate = 0,0
machine_min_travel_rate = 0,0
max_layer_height = 0
max_print_height = 250
min_layer_height = 0.07
nozzle_diameter = 0.4
parking_pos_retraction = 92
pause_print_gcode = M601
print_host = 
printer_model = 
printer_notes = 
printer_settings_id = 
printer_technology = FFF
printer_variant = 
printer_vendor = 
printhost_apikey = 
printhost_cafile = 
remaining_times = 0
retract_before_travel = 2
retract_before_wipe = 0%
retract_layer_change = 1
retract_length = 4
retract_length_toolchange = 10
retract_lift = 0.5
retract_lift_above = 0
retract_lift_below = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0
retract_speed = 40
silent_mode = 1
single_extruder_multi_material = 0
start_gcode = M104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG21 ;metric values\nG90 ;absolute positioning\nM82 ;set extruder to absolute mode\nM107 ;start with the fan off\nG28 X0 Y0 ;move X/Y to min endstops\nG28 Z0 ;move Z to min endstops\nG1 X5 Y10 F1500 ; move to prime\nG1 Z0.2 F3000 ; get ready to prime\nG92 E0 ; reset extrusion distance\nG1 Y80 E10 F600 ; prime nozzle\nG1 Y100 F5000 ; quick wipe\nG92 E0 ; reset extrusion distance\nG1 F9000
template_custom_gcode = 
thumbnails = 16x16,220x124
toolchange_gcode = 
use_firmware_retraction = 0
use_relative_e_distances = 0
use_volumetric_e = 0
variable_layer_height = 1
wipe = 1
z_offset = 0

[physical_printer:Octoprint]
host_type = octoprint
preset_name = Anet ET4
print_host = 
printer_technology = FFF
printhost_apikey = 
printhost_authorization_type = key
printhost_cafile = 
printhost_password = 
printhost_port = 
printhost_user = 

[presets]
print = 0.20mm - Default
sla_print = 
sla_material = 
printer = Anet ET4
filament = TuCAB PETG
physical_printer = Octoprint

**Comment by rtyr** [comment]
Thank you, but I will not implement this. I will save it for possible future use though.

Main reasons:
Configuration bundle should be in the structure mentioned here https://github.com/prusa3d/PrusaSlicer/wiki/Vendor-bundles-and-updating-process.

I checked the settings and I see some issues (incorrect number of top/bottom layers, no generic filament profiles (and those TuCAB ones have significantly increased multiplier), inconsistent retraction settings (printer settings vs filament overrides), etc.
