### ISSUE TITLE
[Config] Caribou 420 Duet 2 Wifi

### ISSUE THREAD

**Issue by bbday** [prusa3d/PrusaSlicer-settings#130]
Just wanna share printer config for caribou 420 duet 2 wifi (nozles and filaments use default profile mk3s) you can use same config for 210 and 310 versions just change max Z. 
Probably will work also for Zaribo duet 2 wifi same config

https://justpaste.it/899qt

**Comment by rtyr** [comment]
Thanks, we may use Caribou bundle from https://github.com/slic3r/slic3r-profiles in the future, altough I am not so sure it is needed since those printers are basically modified MK3s. I am closing this issue, since this config will be not used.
