### ISSUE TITLE
Add „das filament PETG“ to PrusaResearch 

### ISSUE THREAD

**Issue by northerx** [prusa3d/PrusaSlicer-settings#132]
The Filament „das filament PETG“ is available for creality printers. So print property's should be known ;) Unfortunately not yet for Prusa printers.

**Comment by rtyr** [comment]
> So print property's should be known ;)

That profile was added by community, specifically for Creality printers. Closing.

**Comment by rtyr** [comment]
That being said, I will likely add profile for this filament in the future.

**Comment by rtyr** [comment]
This filament was not yet added for our printers.

**Comment by rtyr** [comment]
Tested filament profile for our printers would certainly help. Recently added filament profiles for add:north and Extrudr filaments were provided directly by manufacturer.

**Comment by Skaronator** [comment]
Just usw Generic PETG. Custom profiles are mostly overrrated IMO and Generic works 99% just as well.
