### ISSUE TITLE
Reduce minimum exposure time on the prusa SL1S from 1 second to less

### ISSUE THREAD

**Issue by CanineTunic** [prusa3d/PrusaSlicer-settings#142]
Currently, the Prusa SL1S is limited to a minimum exposure time of 1 second. I think this should be reduced to something closer to 0.2 seconds because some materials have extremely fast curing times, especially at 0.025mm layer height. This can be gotten around by modifying the default settings in prusaslicer, but it is still not possible to do a resin calibration test print with a layer time lower than 1 second and this could cause some users to have difficulty calibrating their resin.

**Comment by rtyr** [comment]
It was forwarded to SLA team, closing here.
