### ISSUE TITLE
[Profile] Ultimaker 2

### ISSUE THREAD

**Issue by foreachthing** [prusa3d/PrusaSlicer-settings#143]
Here's my long due Ultimaker 2 profile.
Unfortunately I can't get the bed texture to work ... maybe some could point me into the right direction?!

[Ultimaker.zip](https://github.com/prusa3d/PrusaSlicer-settings/files/7413297/Ultimaker.zip)

**Comment by rtyr** [comment]
Thanks, I will check it.

**Comment by rtyr** [comment]
The problem was with the bed model (it was only a face and not centered). Updated model is attached below.

I noticed small error in 0.12mm profile (layer height is set to 0.1mm), I can fix that. Can we add more material profiles? There is only PLA profile included. Some basic PETG profile at least? :). 

[ultimaker2b.zip](https://github.com/prusa3d/PrusaSlicer-settings/files/7449664/ultimaker2b.zip)

**Comment by foreachthing** [comment]
You can do what you want :-)
I only print PLA, so I could not test any other material. I thought the community will add more through PRs... eventually.
Do you want me to update the zip file or can you merge your edits?

**Comment by rtyr** [comment]
> Do you want me to update the zip file or can you merge your edits?

No need, I will do it.

**Comment by foreachthing** [comment]
Question: If I want to add more material to this profile, how would I do that?
Would I do that via PR or upload it here?

I'm currently testing (calibration with SuperSlicer - sorry! ;-) ) new material I got from [3DWare](https://www.3dware.ch/en).

**Comment by rtyr** [comment]
You can upload it here. Exported config ini is fine.

**Comment by rtyr** [comment]
Your profiles are now on master. I added Generic PETG and Generic ABS filament profiles (based on the official Cura profiles). Other than that I fixed some minor things in the ini and modified the thumbnail (transparent background).

**Comment by foreachthing** [comment]
I just got the new build with this profile included. All looks good except:
* that the Ultimaker 2 has ø 3 mm (or ø 2.85 mm) filament. All the generic filament is set to ø 1.75 mm.

**Comment by rtyr** [comment]
Fixed. I also fixed ABS density.

**Comment by rtyr** [comment]
Included in 2.4.0-beta2. Closing.
