### ISSUE TITLE
Missing Voron Trident 350mm in Configuration Assistant

### ISSUE THREAD

**Issue by tkodev** [prusa3d/PrusaSlicer-settings#154]
**Is your feature request related to a problem? Please describe.**
- The configuration assistant is missing the Voron Trident (v1) 350mm printer selection, but has the 250mm and 300mm.

**Describe the solution you'd like**
- Add a preset for that printer, based on the 300mm one.

**Describe how it would work**
Be as descriptive as your skill level allows you.
- Take the 300mm preset for Voron Trident, and extrapolate the printer move limits to that of the 350mm.
- Add a 350mm bed model.

**Describe alternatives you've considered**
- I can make this on my own, but having it in the presets is nice because a 350mm Voron Trident is officially part of the trident design lineup.

**Additional context**
Add any other context or paint drawing about the feature request here.
- Originally posted in https://github.com/supermerill/SuperSlicer/issues/2595 but I realize the issue is in PrusaSlicer as well.

**Comment by rtyr** [comment]
Added in just released configuration update 1.0.1. Closing.
