### ISSUE TITLE
Anycubic Kossel Linear Plus wrong bed size in settings.

### ISSUE THREAD

**Issue by jamilbn** [prusa3d/PrusaSlicer-settings#161]
The bed size of the Kossel Linear Plus is 229mm and not 240mm or 239mm as it should be.

**Comment by rtyr** [comment]
I don't see such  value in our bundled settings. You are probably using some different settings or old version of Anycubic bundle.

![aklp](https://user-images.githubusercontent.com/36745189/182789001-f60114b0-08f6-45b0-b521-4447e8d1f1c5.jpg)

Closing.
