### ISSUE TITLE
Feature Request: Add 0.6 and 0.8 nozzle profile for Anycubic Kossel Printers

### ISSUE THREAD

**Issue by jamilbn** [prusa3d/PrusaSlicer-settings#164]
The print quality that I'm getting from Prusa Slicer in my Anycubic Kossel Linear Plus is so much better than the print quality I'm getting on CURA. But Cura calculate all the line sizes for change in nozzle diameter. I would like to use multiple nozzle diameters in Prusa Slicer too.

**Comment by rtyr** [comment]
Do you have such profiles? Profiles for 3rd party printers are usually provided by the community.

**Comment by jamilbn** [comment]
I don't have them. Who created the profile for my printer did a great job. I get print quality that I never got with any other software. Tried to create a profile for 0,6 but no sucess yet. If I have them working I'll submit them here. Thanks.
