### ISSUE TITLE
Adding VOXELPLA material to the next prusaslicer build

### ISSUE THREAD

**Issue by VOXELPLA** [prusa3d/PrusaSlicer-settings#165]
I am looking to add a profile for our new filament, VOXELPLA, to the next build of prusaslicer. How can I do this?

**Comment by rtyr** [comment]
You can attach exported profile here (zip), I will check it.

**Comment by VOXELPLA** [comment]
Got it; thank you so much. I have attached two presets for our filament, one for Creality and Anycubic, and one general one with our recommended Temp. Let me know if there is any problem.

[PrusaSlicer_config_bundle VOXELPLA PLUS.zip](https://github.com/prusa3d/PrusaSlicer-settings/files/9384108/PrusaSlicer_config_bundle.VOXELPLA.PLUS.zip)

**Comment by rtyr** [comment]
What is brand or manufacturer of this filament (we need some vendor for filament wizard)?

**Comment by VOXELPLA** [comment]
The brand and manufacturer is VOXELPLA; all of the filament is PLA 1.75mm, and we offer 5 colors, all included in the zip file above. Let me know if there is anything else we can assist you with.

**Comment by rtyr** [comment]
I will add the profile to the Anycubic and Creality bundle. We don't have general filament library yet, so it will be available only for Anycubic and Creality printers.

**Comment by VOXELPLA** [comment]
Got it. Thank you so much; we are currently testing the Prusa, Ultimaker, and artillery profiles and should have them ready in 2 weeks. When it is ready, should I just add it to this case or open a new issue? Again, really thank you for your help.

**Comment by owengaspard** [comment]
@VOXELPLA per request of @rtyr, I have added your profiles for Creality and Anycubic to my PR. Please see https://github.com/prusa3d/PrusaSlicer/pull/8817.

**Comment by rtyr** [comment]
Anycubic update was already released last week.

**Comment by rtyr** [comment]
Included in the Creality 0.2.2 configuration update. Closing.
