### ISSUE TITLE
Wrong Extruder Clearance in Creality Ender 3 V2 presets

### ISSUE THREAD

**Issue by awabom** [prusa3d/PrusaSlicer-settings#175]
### Description of the bug

The gantry squashed one of the printed objects when using "Complete individual objects" (Sequential printing). The extruder clearance in e.g. "0.36 mm CHUNKY (0.6 mm nozzle) @CREALITY" is set to Height = 34 mm.

Measuring on my Ender 3 V2 (stock), the gantry height is 30 mm, and a bit below that is a belt. Near the left/right edges of the build plate, the height goes even lower.

FYI, Cura has the gantry height set to 25 mm which is maybe a bit conservative, but safe.

![image](https://user-images.githubusercontent.com/42467180/201335114-d2ebb57e-34a2-438a-bc74-fed67ddd08f1.png)

### Project file & How to reproduce

[GantrySquash.zip](https://github.com/prusa3d/PrusaSlicer/files/9989958/GantrySquash.zip)

### Checklist of files included above

- [X] Project file
- [X] Screenshot

### Version of PrusaSlicer

2.5.0+win64

### Operating system

Windows 11 Pro

### Printer model

Creality Ender-3 V2

**Comment by pmjdebruijn** [comment]
I don't disagree, though I still need to think about the values then.

I'll probably fold this into some other changes  I have pending soonish...

@rtyr In the meanwhile can you add thumbnails for ENDER5S1 and SERMOONV1 ? Which min_slic3r_version should I use for adding those?

**Comment by rtyr** [comment]
Thumbnails are ready.

**Comment by rtyr** [comment]
Clearances were update in configuration update 0.2.4
