### ISSUE TITLE
New Elegoo Neptune Printer Profiles

### ISSUE THREAD

**Issue by mlee12382** [prusa3d/PrusaSlicer-settings#179]
There are new models for the Elegoo Neptune 3 printer all 3 of which have Direct Drive and need retraction distances updated to 2.5mm @ 25mm/s as the base speed based on Cura profiles provided by Elegoo. There are also build volume increases on 2 of the models as shown in the provided picture. They can use the current Neptune 3 profile as a base and just update for the DD and new build volumes. The Pro is the same as the base 3 other than being DD. The Plus and Max have larger build volumes and also are DD.
![ElegooNeptune3Chart](https://user-images.githubusercontent.com/89716126/210155169-7bda5c00-c83d-4ff5-82aa-8b7a751d1bc3.jpg)

Thanks for your help :) Btw is there a way to make proposed changes to the profiles and just do a pull request for inclusion?

**Comment by rtyr** [comment]
You can either create a pull request or just attach modified ini/resources here.

**Comment by mlee12382** [comment]
> You can either create a pull request or just attach modified ini/resources here.

Alright I will work on that this weekend :) thanks.

**Comment by mlee12382** [comment]
@rtyr Here is the updated ini file as a txt since github doesn't allow .ini files. I wasn't sure on the Pro / Plus / Max what to do in the notes especially since they are no longer bowden. I wasn't sure what keywords to use / change or if it even matters? I also noticed all of the models are tagged as PRINTER_MODEL_NEPTUNE2D, not sure if that was intentional or an oversight when setting it up initially? I left them as is in case changing them messes up other stuff.
[Elegoo.txt](https://github.com/prusa3d/PrusaSlicer-settings/files/10365266/Elegoo.txt)

**Comment by rtyr** [comment]
> what to do in the notes especially since they are no longer bowden. I wasn't sure what keywords to use / change or if it even matters?

It doesn't matter if it's not used in any condition. I removed it completely.

> I also noticed all of the models are tagged as PRINTER_MODEL_NEPTUNE2D, not sure if that was intentional or an oversight when setting it up.

I changed it according to particular model, but as far as I can see, this keyword is not used anywhere anyway.

Here is the final bundle (it will be compatible with 2.6.0-alpha1 and newer.
[1.0.2.zip](https://github.com/prusa3d/PrusaSlicer-settings/files/10433627/1.0.2.zip)
