### ISSUE TITLE
Ender 5 S1 profil

### ISSUE THREAD

**Issue by Ct87** [prusa3d/PrusaSlicer-settings#182]
Hello

can someone help me with ender 5 s1 profil. I m a noob and just have 2 prusa now i bought ender 5 s1 but i do not want to use cura. prusa slicer is easier

**Comment by rtyr** [comment]
Ender 5 S1 is already included in 2.6.0 alpha releases.

Current release can be downloaded here:
https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.6.0-alpha4
