### ISSUE TITLE
missing/empty (first) layer

### ISSUE THREAD

**Issue by DanBowk** [prusa3d/PrusaSlicer-settings#184]
I get an "empty layer between 0 and .5" when using any variant of 2.6. This is with downloaded models and ones I've created.
![Screenshot 2023-02-23 105624](https://user-images.githubusercontent.com/124794658/220887423-608335ee-c6ad-4633-8ace-a3412ceb4b14.jpg)

**Comment by rtyr** [comment]
Please provide your 3MF project file.

**Comment by DanBowk** [comment]
> Please provide your 3MF project file.

Where do I add it? I've tried adding it in teh comments but it says file type not supported! It is a .3mf file.

Sorry, complete newbie to github.

**Comment by rtyr** [comment]
Archive it to the zip first.

**Comment by DanBowk** [comment]
[AK_Bat_helm_4.0_Back.zip](https://github.com/prusa3d/PrusaSlicer-settings/files/10824343/AK_Bat_helm_4.0_Back.zip)

**Comment by rtyr** [comment]
The model have a lot of errors. The model needs to be repaired first.
