### ISSUE TITLE
New profiles for Spectrum filaments

### ISSUE THREAD

**Issue by bartosz-spectrumfilaments** [prusa3d/PrusaSlicer-settings#185]
Hi, I modified latest config file and added printing profiles to Prusa Mini and i3 family to few filaments from Spectrum. Please review them and let me know if I must change anything else. Changes were made from line 2811 to 2963.
[1.5.6 - spectrum filaments.ini.zip](https://github.com/prusa3d/PrusaSlicer-settings/files/10824439/1.5.6.-.spectrum.filaments.ini.zip)

**Comment by rtyr** [comment]
Spectrum filaments were added to 2.6.0-alpha5 and higher via on-line update.
