### ISSUE TITLE
Prusa MK3s 0.25 nozzle PETG temperature

### ISSUE THREAD

**Issue by lukasradek** [prusa3d/PrusaSlicer-settings#191]
I have been happy printing Prusament PETG with base profiles since 2020 with great results.
Now I came back to PETG after about a year and done some successful prints with 0.4 nozzle and then switched to 0.25 and got huge problems with adhesion even on large surface areas. Since I haven't changed anything in my settings / printer I assumed some "hardware misalignement" after the nozzle change. After about 4 failures I managed to make the first layer somewhat stick (few small imperfections but nothing compared to just tearing off previously) - albeit it requried vigorous steel sheet cleaning and ridiculous first layer squish. But even then the second/third layer just refused to stick altogether. So I checked the temps and was surprised that I am printing PETG at 230°C.

And so... 230°C in Prusament PETG for MMU is just insufficient. Looks like you can get away with it with 0.4 nozzle but 0.25 just does not work (for me... bed at 85-90, 21°C room temperature, stock prusa mk3s+).

I have seen it discussed here and at one other place and it was sweeped under the rug with explanation that it increases MMU reliability.
At least in my case MMU is just fine with 250°C and even if the reliability is higher at 230°C there is not really a point to it if the rest of the printer "doesn't work".

**Comment by rtyr** [comment]
Please provide some example project file which you are unable to print with default temps.

**Comment by lukasradek** [comment]
Literally any that I try.

[For example this one.](https://github.com/prusa3d/PrusaSlicer-settings/files/11304109/petg-mmu-temp-issue.zip)

**Comment by rtyr** [comment]
I was not able to reproduce the issue you are describing across various Prusament PETG colors and printers.

![20230428_152314](https://user-images.githubusercontent.com/36745189/235174117-1afc4080-6ad7-4869-bffc-88dabe8a1592.jpg)

![20230428_161540](https://user-images.githubusercontent.com/36745189/235174112-fe77ae75-2550-4a38-ad0a-d91151c1be1c.jpg)

**Comment by lukasradek** [comment]
Just to be sure... is that a 0.25 nozzle?
If so, that really baffles me what is wrong at my end.

**Comment by rtyr** [comment]
Sure, 0.25mm nozzle, 0.15 layer height. It may be partially clogged nozzle or some thermistor issue. There is also quite big tolerance in thermistor reading (2-3%). We may increase temp a little bit, but it seems the main issue is elsewhere.
