### ISSUE TITLE
Note in the Print With Smile ASA system profile

### ISSUE THREAD

**Issue by zbkingCZ** [prusa3d/PrusaSlicer-settings#200]
Hello!

I noticed a small error in the Note of the ASA Print With Smile filament system profile. 

![Print With Smile ASA Profile](https://github.com/prusa3d/PrusaSlicer-settings/assets/29282782/7b091699-3a93-4129-9d49-dc39a583cb8c)

**Comment by rtyr** [comment]
Fixed
