### ISSUE TITLE
PolyLight 1.0 LW-PLA in Prusa Slicer 2.6.0 for Prusa Mk 4

### ISSUE THREAD

**Issue by PeterWH56** [prusa3d/PrusaSlicer-settings#205]
Could you please contact Prusa and ask them to include Polylight 1.0 LW-PLA as a standard filament option in Prusa Slicer?

**Comment by rtyr** [comment]
You can find profiles for it here https://www.prusa3d.com/product/polylight-1-0-lw-pla-orange-1kg/.

It is not standard filament option because it also requires different print settings, not just filament settings.
