### ISSUE TITLE
Missing Prusament profiles for Prusa XL - 5T 0.6 nozzle?

### ISSUE THREAD

**Issue by ulab** [prusa3d/PrusaSlicer-settings#212]
With the latest configuration update I seem to have "lost" a lot of Prusament profiles for my XL 5 tool with 0.6 mm nozzle.

While I have selected them:

<img width="772" alt="Screenshot 2023-10-12 at 00 09 07" src="https://github.com/prusa3d/PrusaSlicer-settings/assets/504616/4ad5cb8b-0c3b-4ae8-956d-5beb7be4e42b">

They do not show up in the selection box anymore?

<img width="432" alt="Screenshot 2023-10-12 at 00 10 23" src="https://github.com/prusa3d/PrusaSlicer-settings/assets/504616/2fed63d7-7d80-4311-b9fc-fdc2b203468c">

Am I just too tired to see them? ;-)

**Comment by ulab** [comment]
Update: I have deleted the PrusaSlicer Config folder, restarted PrusaSlicer, added the XL 5T 0.6 and some Prusament profiles.

They show up now with the old default config:

<img width="427" alt="Screenshot 2023-10-12 at 00 18 51" src="https://github.com/prusa3d/PrusaSlicer-settings/assets/504616/201b670b-3a1a-409b-807d-d625c8fa21fc">

I then did `Check for Configuration Updates` and upgraded to 1.0.4 (Templates) and 1.10.1 (Prusa Research). After that they were gone:

<img width="425" alt="Screenshot 2023-10-12 at 00 20 22" src="https://github.com/prusa3d/PrusaSlicer-settings/assets/504616/2807d751-1063-44ab-a937-9f1e6f4aae2a">

**Comment by ulab** [comment]
Ok, this is getting weird. 

It seems like the profiles got unselected in the Configuration assistant too and they are back after re-selecting them.

That never happened during a Configuration update?

**Comment by rtyr** [comment]
Previously all filament profiles were shared between XL and MK4 printers. It changed since configuration update 1.10.0, where we internally split XL and MK4 filament profiles (XL needs some special parameters for new ramming feature). That is the reason why XL users had to re-enable some filament profiles in the configuration wizard. 

It was mentioned in release note for 1.10.0 update. You might missed this warning, if you updated straight to 1.10.1.

**Comment by ulab** [comment]
That might be the reason. Especially when you start from scratch like I did as a test you'll skip the release notes from 1.10.0. 

It will fix automatically with the next PS release which should come with the new profiles from the start, so I'll just close this issue.

**Comment by ulab** [comment]
PS: [1.10.0 Release Notes](https://files.prusa3d.com/?latest=slicer-profiles&lng=en_US) didn't really give a "warning" on this:

> - Enabled XL ramming feature for most filament types (all except PLA and flexibles). This feature reduces strings on the prime/wipe tower (Prusa XL Multi-Tool).
> - Added new profiles for Prusa MINI Input Shaper (Alpha). Added profiles for additional nozzle diameters.

**Comment by rtyr** [comment]
It did.

This is the notification text, which was visible in the PrusaSlicer. It is non-detailed release note, which is always visible.

`Added new profiles for Prusa MINI Input Shaper (Alpha). Enabled XL ramming feature. Prusa XL users may need to re-enable filament profiles in configuration wizard.`

The text is taken from 
https://github.com/prusa3d/PrusaSlicer-settings/blob/master/live/PrusaResearch/index.idx

**Comment by rtyr** [comment]
We will try to improve the wizard, so it behaves better with fresh install.
