### ISSUE TITLE
Change value for Solid infill in 0.2mm SOLUBLE INTERFACE @XLIS 0.4

### ISSUE THREAD

**Issue by mdjurfeldt** [prusa3d/PrusaSlicer-settings#214]
### Description of the bug

The problem is that the speed 60mm/s, which is default for Solid infill in the 0.2mm SOLUBLE INTERFACE @XLIS 0.4 profile (and possibly other profiles as well) is particularly unsuitable for the XL. Especially if your model is at the rear part of the print sheet, this speed induces strong resonances in the whole printer (at least my printer).

I suggest that you change it to 80mm/s (same value as Top solid infill in this profile).

### Project file & How to reproduce

Slice any model with Solid infill using the profile mentioned. Then listen to the sound.

### Checklist of files included above

- [ ] Project file
- [ ] Screenshot

### Version of PrusaSlicer

Version 2.7.0-alpha1+linux-x64-GTK3

### Operating system

Debian Bookworm

### Printer model

5-tool XL

**Comment by rtyr** [comment]
Changed to 70mm/s for now. It needs to be fairly slow since this speed is also used for 1st non-soluble layer printed on soluble interface.
Thanks.
