### ISSUE TITLE
double same filament presets shown

### ISSUE THREAD

**Issue by MihRei** [prusa3d/PrusaSlicer-settings#216]
### Description of the bug

for Original Prusa Mini Imput Shaper alpha 0.6 nozzle in the filament section apeears same filament type double but just for this printer preset

### Project file & How to reproduce

![image_2023-10-29_182315014](https://github.com/prusa3d/PrusaSlicer/assets/80645548/001d722b-9fde-409a-a69e-c115ecbc487c)

![image_2023-10-29_182342744](https://github.com/prusa3d/PrusaSlicer/assets/80645548/cb38b6ad-71ab-4e72-a86a-634e906c75b0)

 compared to the same printer but other preset o.4 mm nozzle

![image_2023-10-29_182443430](https://github.com/prusa3d/PrusaSlicer/assets/80645548/8226de29-a8ee-4457-863c-132d75268cc9)

![image](https://github.com/prusa3d/PrusaSlicer/assets/80645548/12011992-bc42-4677-a0db-d2a14b3820e6)

### Checklist of files included above

- [ ] Project file
- [ ] Screenshot

### Version of PrusaSlicer

PrusaSlicer-2.7.0-alpha1+win64-202310191602_signed

### Operating system

windows 11

### Printer model

prusa MINI +

**Comment by rtyr** [comment]
Thanks, we will fix it in the next configuration update.
