### ISSUE TITLE
Prusa Slicer error when saving gcode files due to new .bgcode binary half default

### ISSUE THREAD

**Issue by dimitarsp** [prusa3d/PrusaSlicer-settings#223]
### Description of the bug

The new version of prusa slicer defaults to saving files to .bgcode, but by default saving to .bgcode is disabled, leading to almost always getting an error, just by doing what I was doing before, exporting to flash drive.

Now, instead of simply exporting, i hit export, input a name, hit save, and i get the error. And then i go again, and have to consciously select the third item in the list, .gcode.

Somehow with this bug the time to process 3d prints has significantly extended. 

It would be best to set the default of saving back to .gcode or to give us an option to choose what the default export file type should be. 

### Project file & How to reproduce

Open a new file, import stl, slice it, and export to computer or disk. Type in a name, and you get an error, because .bgcode is not enabled in the settings. 

<img width="428" alt="prusa-slicer_XmmOqDm0bE" src="https://github.com/prusa3d/PrusaSlicer/assets/2496411/4737f196-038d-42ed-b1a0-65ae1a66d657">

### Checklist of files included above

- [X] Project file
- [X] Screenshot

### Version of PrusaSlicer

2.7.0

### Operating system

Windows 11

### Printer model

prusa mini+

**Comment by rtyr** [comment]
I checked and you are right, even though this issue is present only in "old" non input shaper profiles for 0.6 nozzle. We will fix that with configuration update. Thank you for reporting it.

**Comment by rtyr** [comment]
If you have up-to-date firmware (5.1.0), you can enable "MINI Input Shaper" through configuration wizard.

**Comment by rtyr** [comment]
Fixed with configuration update 1.11.6.
