### ISSUE TITLE
Add a button

### ISSUE THREAD

**Issue by ran075** [prusa3d/PrusaSlicer-settings#232]
Hi all!
The most popular action is to change the settings, and then go to the table tab to slice and check. It would be great to make such a button on the settings tab - "slice and look at the table". This will save a lot of clicks. Thanks.

**Comment by rtyr** [comment]
You can set the settings to be visible on a separate non-modal window, so you don't have to switch between table and settings.

![nonmod](https://github.com/prusa3d/PrusaSlicer-settings/assets/36745189/346b23a5-b831-42b1-89ca-cf3d2964b566)
