### ISSUE TITLE
add the 0.30 Printer settings profile

### ISSUE THREAD

**Issue by cgerrist** [prusa3d/PrusaSlicer-settings#251]
Hello,

In the mk3s 0.40 printer settings I had the 0.30 Printer Settings profile.
This was an perfect setting for speed and quality.
Could this profile add in the next release?

Chris Gerrist

**Comment by cgerrist** [comment]
I forgot to write my printer version. I have a mk3.5 printer

**Comment by rtyr** [comment]
It made sense on MK3S, but not so much on MK3.5, since even 0.20 SPEED already prints so fast, that it is close to the volumetric speed limits of the hotend (how fast can be filament melted). 0.3 layer height would need to be printed much slower.

**Comment by cgerrist** [comment]
Hi,

Today I made a print profile 0.30 for the 0.4 nozzle. Same as the Prusa mk3s profile.
The print looks beautiful. I didn’t had any problems at all.

Chris Gerrist

**Comment by rtyr** [comment]
It will print fine, but slower. The speed is limited automatically by volumetric speed limit.

**Comment by rtyr** [comment]
more layer heights were added for high-flow nozzle profile variants
