### ISSUE TITLE
No printer-profile für MK4 with MMU3 without Inputshaper

### ISSUE THREAD

**Issue by facebraker** [prusa3d/PrusaSlicer-settings#254]
Are there any preparations to offer a pre-made printer profile for the MK4 with MMU3 **without** Input Shaper in PrusaSlicer? After all, there are already two profiles available for the standalone MK4. I prefer the convenient approach through the printer profile.

Thank you!!!

**Comment by rtyr** [comment]
That is not planned. On the contrary, we will possibly remove legacy "non-IS" profiles for MK4, or move them to some legacy section of the wizard. Input shaper is firmware feature which is always active, no matter which print profiles are used. Old "non-IS" print profiles were meant for early MK4 FW versions, where IS was not supported yet.
