### ISSUE TITLE
Add Generic PLA+ and PLA Silk to create custom profiles

### ISSUE THREAD

**Issue by Big-Channie** [prusa3d/PrusaSlicer-settings#271]
Would be really nice to have better filament types available to use as a baseline for custom profiles. No PLA+, silk, wood, or other modified filament types are available currently.

**Comment by rtyr** [comment]
> No PLA+, silk, wood, or other modified filament types are available currently.

There are already various PLA+, silk, wood filaments within Prusa printers and also within templates. Not sure what do you mean.
