### ISSUE TITLE
Incorrect cooling Settings on duel extruder setups

### ISSUE THREAD

**Issue by Thirkell** [prusa3d/PrusaSlicer-settings#40]
I have a duel extruder setup. I have noticed that slicing a part for printing using only extruder 2 uses the filament cooling setting for whatever may be set in extruder 1 even though it is not in use. 
Using version 1.41.0+win64

**Comment by rtyr** [comment]
I believe this issue was fixed and is not present in the latest PrusaSlicer. In case of any related issues, please create issue here https://github.com/prusa3d/PrusaSlicer. Closing.
