### ISSUE TITLE
marlin stock tevo tarantula controller buffer issue / crash at 500-1000 lines .  

### ISSUE THREAD

**Issue by tony978** [prusa3d/PrusaSlicer-settings#51]
I am running a dual extruder with a single nozzle. This is my first dual print with the software , I've been running s3d without issues single extruder with no "too many lines to buffer, cut off" errors. For whatever reason, that is what I'm getting with this code around when it is going to print with the second tool or it just restarts the controller. I'm running octaprint and slowed the baud rate with no luck and have slowed feed rates alittle . attached is the gcode . 
[cali_1-R - Copy.txt](https://github.com/prusa3d/Slic3r-settings/files/2426404/cali_1-R.-.Copy.txt)

 edit: upload the wrong file 
[cali_1-R correct file .txt](https://github.com/prusa3d/Slic3r-settings/files/2429968/cali_1-R.txt)

**Comment by rtyr** [comment]
I don't think, that this is PrusaSlicer-settings related. Closing.
