### ISSUE TITLE
how to raise and move dual nozzles when they are switching

### ISSUE THREAD

**Issue by bman2000** [prusa3d/PrusaSlicer-settings#52]
I am having a problem with my code when I use my two nozzles to print two different parts on the same build surface. When the nozzles change ( tool change) it happens over the printed part and the nozzles melt the part that that has been printed.

Is there away to have this heating happen where both nozzles are clear of the part? Also, How do I avoid the nozzles passing over a printed part when either one of them is hot?

I have been looking to add some custom gcode but I am still learning and I have no idea how do this yet.
Thank you

**Comment by rtyr** [comment]
I believe it can be achieved by using custom toolchange g-code or by using of wipe tower. Anyway, this repository is meant for settings which are bundled with the PrusaSlicer. Closing.
