### ISSUE TITLE
Default Sequential Print Extruder Sizes Too Small (Mk3)

### ISSUE THREAD

**Issue by uniacke1** [prusa3d/PrusaSlicer-settings#62]
The default radius and height for sequential printing (20mm) are too small for the stock PRUSA extruder, especially with the R3 fan orientation. This could cause the printer to crash into prints if a user enables sequential printing without checking those values.

**Comment by qqgg231** [comment]
Current default settings are not usable, not allow to print: 

<img width="960" alt="2019-04-21 16_34_49-Greenshot" src="https://user-images.githubusercontent.com/11590960/56471662-41c5f180-6455-11e9-95eb-720b1cd25784.png">

**Comment by rtyr** [comment]
Default values are now changed to 45/25.

**Comment by uniacke1** [comment]
W00t, thanks!
