### ISSUE TITLE
[Suggestion] Output Filename

### ISSUE THREAD

**Issue by cycl0ne** [prusa3d/PrusaSlicer-settings#71]
You lately changed the filename output to the time being used. Thats wonderfull and this took me to dig more into the filename thing. So my request is as follow, could you change the default output name to:
{input_filename_base}{layer_height}mm{filament_settings_id[0]}{printer_model}{print_time}.gcode

filament_settings_id instead of filament_name?

You may ask why? Easy: One has different PLA which is used, with different temperature. If the output file is just:

name_0.2mm_PLA_MK3S_27m.gcode

its not usable, but when used the filament_settings_id:

name_0.2mm_PRUSA_PLA_MK3S_27m.gcode
name_0.2mm_GENERIC_PLA_MK3S_27m.gcode

its makes more sense.

**Comment by rtyr** [comment]
Hi. I am affraid that output filename would be too long with filament_settings_id. But you can use your own custom filament type now. 

![ftype](https://user-images.githubusercontent.com/36745189/59021665-844c5d80-884c-11e9-935f-36753d0be838.jpg)

**Comment by rtyr** [comment]
Can I close this issue?

**Comment by cycl0ne** [comment]
Yes, of course.
