### ISSUE TITLE
Prussia slicer version 2.0 support enforcer placement

### ISSUE THREAD

**Issue by bman2000** [prusa3d/PrusaSlicer-settings#72]
Placement of enforcer is very finicky.
Moving enforcer, to position can be diificult when rotating the model as small enforcer movements van drastically kick enforcer away from model.

**Comment by rtyr** [comment]
I believe this issue should be posted at https://github.com/prusa3d/PrusaSlicer. Please move it there, if the problem is still present in the latest PrusaSlicer 2.1.0.

**Comment by bman2000** [comment]
This is still an issue on the newly released version.

Unfortunately I do not know how to move the issue as requested.

**Comment by rtyr** [comment]
Closing here. Feel free to reopen issue at https://github.com/prusa3d/PrusaSlicer.
