### ISSUE TITLE
AmazonBasics has changed manufacturer.  Overture is the old AmazonBasics.

### ISSUE THREAD

**Issue by talldonkey** [prusa3d/PrusaSlicer-settings#89]
### Version
2.2.0 Alpha 2

### Behavior
Just wanted to make the Prusa team aware that AmazonBasics filament has re-launched in the USA with a different manufacturer, so the AmazonBasics  filament profiles may no longer be valid as times go on and the new manufacturer's filament becomes established as the 'new amazonbasics'.  It is also unclear which AmazonBasics this profile is for.

The Old AmazonBasics filament has resurfaced on Amazon as the "Overture" brand.  The community seems to have concluded that Overture used to be Amazon
basics based on multiple posts comparing the two, the appearance and features of the spool.  (https://www.reddit.com/r/3Dprinting/search/?q=overture&restrict_sr=1)

Links:
'Old' AmazonBasics aka Overture, https://www.amazon.com/dp/B07PFS2R12

"New" Rebranded AmazonBasics via different manufacturer:
https://www.amazon.com/AmazonBasics-Printer-Filament-1-75mm-Spool/dp/B07T616NXL

This request is to 'handle' this in some way to make it clear which filament the profiles are for.  The old amazonbasics/overture or the new one. 

For example, rename current AmazonBasics profile in a way to include "Overture" may be one possible approach.  We may want to indicate that this profile either does (or doesn't) work with the 'new' Amazonbasics

**Comment by rtyr** [comment]
Overture profile was added. Thank you. Closing.
