### ISSUE TITLE
Change support contact Z distance to 0.2mm in default profiles

### ISSUE THREAD

**Issue by yoyo42** [prusa3d/PrusaSlicer-settings#91]
### Version
v2.20+win64

### Operating system type + version
Win10 x64

### 3D printer brand / version + firmware version (if known)
i3 mk3 upgraded to mk3s

### Behavior
The default 'Contact Z distance' for supports in all Prusa supplied profiles seems to be 0.1mm, it also has 0 (soluble) and 0.2 (detachable) in the drop down. I very rarely see any mention of anyone using soluble supports, and 0.1 does not seem to detach cleanly for most filaments I've tried, so should 0.2 be the default? I have to copy every profile I use just so I can set 0.2 as the default.

Probably counts as a feature request, or else it should be the topic of a poll?

**Comment by rtyr** [comment]
Contact Z distance value is always some compromise between quality and ease of the removal. There are opposite opinions about this. It also depends on what material is being used. As you can see on the photo, increased contact Z distance has significant impact on quality. Anyway, we will leave it as it is for now. Closing. 

![0102com_1900t](https://user-images.githubusercontent.com/36745189/82053089-0a0f9480-96bd-11ea-8f57-b139163084c4.jpg)
