### ISSUE TITLE
Home axes before wait for temperatures

### ISSUE THREAD

**Issue by espr14** [prusa3d/PrusaSlicer-settings#93]
### Version
PrusaSlicer-2.2.0+win64-202003211145

### Operating system type + version
Win10 x64

### 3D printer brand / version + firmware version (if known)
MINI 4.0.5
i3 MK3S 3.9.0

### Behavior
Default profile:
1. set temperatures
2. wait for temperatures
3. home
4. MBL

Proposed profile:
1. set temperatures
2. home
3. wait for temperatures
4. MBL

_Is this a new feature request?_ **YES**

#### Project File (.3MF) where problem occurs
N/A

**Comment by rtyr** [comment]
I don't like the idea of homing Z with cold nozzle (there can be some hard filament protruding from the nozzle). Overall I don't think such change is needed and I am afraid lot of our customers would be confused with such a change. I also think that some people are used to clean the bed before preheat phase is finished.

I will keep it in mind for future changes, but I am not going to change the order now. Closing.
