### ISSUE TITLE
FEATURE REQUEST: Prusa purchased .5 nozzle support in Slicer and MK3s firmware

### ISSUE THREAD

**Issue by danroesch** [prusa3d/PrusaSlicer-settings#99]
### Version
2.2.0

### Operating system type + version
agnostic

### 3D printer brand / version + firmware version (if known)
MK3s 3.9.0

### Behavior
1) Need preset for .5 nozzle in Slicer. Prusa sells the .5 Nozzle but not easily configured.

2) Firmware in MK3s needs to be able to select .5 nozzle in settings

3) 1st layer calibration or .5 nozzle needs to be supported. So we don't have to make our own gcode

_Is this a new feature request?_

Yes

You all make amazing printers and software, thanks for all your hard work!

Dan

**Comment by rtyr** [comment]
I will close this and leave https://github.com/prusa3d/PrusaSlicer-settings/issues/111 open.
